if(EXISTS "/Users/shaiiko/Vesper/build-fuzz/vesper_tests-b12d07c_tests.cmake")
  include("/Users/shaiiko/Vesper/build-fuzz/vesper_tests-b12d07c_tests.cmake")
else()
  add_test(vesper_tests_NOT_BUILT-b12d07c vesper_tests_NOT_BUILT-b12d07c)
endif()
